/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { NewPlaylistAlbumDto } from './newPlaylistAlbumDto';
import type { TrackIdDto } from './trackIdDto';

export interface AddPlaylistTracksDto {
  tracks: TrackIdDto[] | null;
  albums: NewPlaylistAlbumDto[] | null;
}
