/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { AlbumArtist } from './albumArtist';
import type { AttributeMap } from './attributeMap';
import type { Identity } from './identity';
import type { Track } from './track';

export interface Album {
  uuid: string | null;
  attributes: AttributeMap | null;
  identities: Identity[] | null;
  tracks: Track[] | null;
  artists: AlbumArtist[] | null;
}
