/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { EphemeralSource } from './ephemeralSource';
import type { EphemeralTrack } from './ephemeralTrack';

export interface AlbumEphemeralContent {
  source: EphemeralSource;
  tracks: EphemeralTrack[];
}
