/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { Task } from './task';

export interface AllTasksResponse {
  pluginTasks: Task[];
  systemTasks: Task[];
}
