/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { Album } from "./album";
import type { AttributeMap } from "./attributeMap";
import type { Identity } from "./identity";
import type { Track } from "./track";

export interface Artist {
	uuid: string;
	attributes: AttributeMap | null;
	/** @nullable */
	identities: Identity[] | null;
	/** @nullable */
	tracks: Track[] | null;
	/** @nullable */
	albums: Album[] | null;
}
