/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */

export interface AttributeUploadSessionResponse {
  key: string;
  extension: string;
  uuid: string;
  url: string;
}
