/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */

export type AttributeEntity = typeof AttributeEntity[keyof typeof AttributeEntity];


export const AttributeEntity = {
  track: 'track',
  artist: 'artist',
  album: 'album',
} as const;
