/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type AttributeType = typeof AttributeType[keyof typeof AttributeType];


export const AttributeType = {
  string: 'string',
  integer: 'integer',
  decimal: 'decimal',
  boolean: 'boolean',
  buffer: 'buffer',
} as const;
