/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { BooleanWorkflowStepOptionValueType } from './booleanWorkflowStepOptionValueType';

export interface BooleanWorkflowStepOptionValue {
  id: string;
  type: BooleanWorkflowStepOptionValueType;
  value: boolean | null;
}
