/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { AttributeEntity } from './attributeEntity';

export interface BooleanSmartPlaylistFilter {
  uuid: string;
  entityType: AttributeEntity;
  attributeKey: string;
  attributeType: 'boolean';
  inverse: boolean;
  value: boolean | null;
}
