/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */

export type BooleanWorkflowStepOptionValueType = typeof BooleanWorkflowStepOptionValueType[keyof typeof BooleanWorkflowStepOptionValueType];


export const BooleanWorkflowStepOptionValueType = {
  boolean: 'boolean',
} as const;
