/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */
import type { BooleanAttributeType } from './booleanAttributeType';

export interface BooleanAttribute {
  type: BooleanAttributeType;
  pluginId: string | null;
  sourceId: string | null;
  formatterPluginId: string | null;
  formatterSourceId: string | null;
  values: boolean[];
  formatted: string[];
}
