/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type BooleanSearchAttributeDtoType = typeof BooleanSearchAttributeDtoType[keyof typeof BooleanSearchAttributeDtoType];


export const BooleanSearchAttributeDtoType = {
  boolean: 'boolean',
} as const;
