/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { BooleanSystemConfigOptionType } from './booleanSystemConfigOptionType';

export interface BooleanSystemConfigOption {
  type: BooleanSystemConfigOptionType;
  key: string;
  supportsMultiple: boolean;
  values: boolean[];
}
