/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type BooleanWorkflowStepOptionValueDtoType = typeof BooleanWorkflowStepOptionValueDtoType[keyof typeof BooleanWorkflowStepOptionValueDtoType];


export const BooleanWorkflowStepOptionValueDtoType = {
  boolean: 'boolean',
} as const;
