/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */

export type BooleanSmartFilterDtoAttributeType = typeof BooleanSmartFilterDtoAttributeType[keyof typeof BooleanSmartFilterDtoAttributeType];


export const BooleanSmartFilterDtoAttributeType = {
  boolean: 'boolean',
} as const;
