/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { BooleanSearchAttributeDtoEntityType } from './booleanSearchAttributeDtoEntityType';
import type { BooleanSearchAttributeDtoType } from './booleanSearchAttributeDtoType';

export interface BooleanSearchAttributeDto {
  entityType: BooleanSearchAttributeDtoEntityType;
  type: BooleanSearchAttributeDtoType;
  key: string;
  exists?: boolean;
  boolean?: boolean;
}
