/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type BooleanUpdateSystemConfigOptionDtoType = typeof BooleanUpdateSystemConfigOptionDtoType[keyof typeof BooleanUpdateSystemConfigOptionDtoType];


export const BooleanUpdateSystemConfigOptionDtoType = {
  boolean: 'boolean',
} as const;
