/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type BooleanSmartFilterDtoEntityType = typeof BooleanSmartFilterDtoEntityType[keyof typeof BooleanSmartFilterDtoEntityType];


export const BooleanSmartFilterDtoEntityType = {
  track: 'track',
  artist: 'artist',
  album: 'album',
} as const;
