/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { BooleanAttributeType } from './booleanAttributeType';

export interface BooleanAttribute {
  type: BooleanAttributeType;
  pluginId: string;
  sourceId: string;
  formatted: string[] | null;
  values: boolean[];
}
