/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { BooleanSmartFilterDtoAttributeType } from './booleanSmartFilterDtoAttributeType';
import type { BooleanSmartFilterDtoEntityType } from './booleanSmartFilterDtoEntityType';

export interface BooleanSmartFilterDto {
  entityType: BooleanSmartFilterDtoEntityType;
  attributeType: BooleanSmartFilterDtoAttributeType;
  attributeKey: string;
  inverse: boolean;
  value?: boolean;
}
