/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { BooleanWorkflowStepOptionValueDtoType } from './booleanWorkflowStepOptionValueDtoType';

export interface BooleanWorkflowStepOptionValueDto {
  id: string;
  type: BooleanWorkflowStepOptionValueDtoType;
  value: boolean | null;
}
