/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */

export type BooleanSystemConfigOptionType = typeof BooleanSystemConfigOptionType[keyof typeof BooleanSystemConfigOptionType];


export const BooleanSystemConfigOptionType = {
  boolean: 'boolean',
} as const;
