/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */

export type BooleanSearchAttributeDtoEntityType = typeof BooleanSearchAttributeDtoEntityType[keyof typeof BooleanSearchAttributeDtoEntityType];


export const BooleanSearchAttributeDtoEntityType = {
  track: 'track',
  artist: 'artist',
  album: 'album',
} as const;
