/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */

export type BufferSmartFilterDtoAttributeType = typeof BufferSmartFilterDtoAttributeType[keyof typeof BufferSmartFilterDtoAttributeType];


export const BufferSmartFilterDtoAttributeType = {
  buffer: 'buffer',
} as const;
