/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */

export type BufferSearchAttributeDtoType = typeof BufferSearchAttributeDtoType[keyof typeof BufferSearchAttributeDtoType];


export const BufferSearchAttributeDtoType = {
  buffer: 'buffer',
} as const;
