/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */

export type BufferSearchAttributeDtoEntityType = typeof BufferSearchAttributeDtoEntityType[keyof typeof BufferSearchAttributeDtoEntityType];


export const BufferSearchAttributeDtoEntityType = {
  track: 'track',
  artist: 'artist',
  album: 'album',
} as const;
