/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { BufferSearchAttributeDtoEntityType } from './bufferSearchAttributeDtoEntityType';
import type { BufferSearchAttributeDtoType } from './bufferSearchAttributeDtoType';

export interface BufferSearchAttributeDto {
  entityType: BufferSearchAttributeDtoEntityType;
  type: BufferSearchAttributeDtoType;
  key: string;
  exists?: boolean;
}
