/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { BufferSmartFilterDtoAttributeType } from './bufferSmartFilterDtoAttributeType';
import type { BufferSmartFilterDtoEntityType } from './bufferSmartFilterDtoEntityType';

export interface BufferSmartFilterDto {
  entityType: BufferSmartFilterDtoEntityType;
  attributeType: BufferSmartFilterDtoAttributeType;
  attributeKey: string;
  inverse: boolean;
}
