/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { AttributeEntity } from './attributeEntity';

export interface BufferSmartPlaylistFilter {
  uuid: string;
  entityType: AttributeEntity;
  attributeKey: string;
  attributeType: 'buffer';
  inverse: boolean;
}
