/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */

export type BufferAttributeType = typeof BufferAttributeType[keyof typeof BufferAttributeType];


export const BufferAttributeType = {
  buffer: 'buffer',
} as const;
