/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { CustomBooleanAttributeDto } from './customBooleanAttributeDto';
import type { CustomDecimalAttributeDto } from './customDecimalAttributeDto';
import type { CustomIntegerAttributeDto } from './customIntegerAttributeDto';
import type { CustomStringAttributeDto } from './customStringAttributeDto';

export interface CreatePlaylistDto {
  attributes: (CustomStringAttributeDto | CustomBooleanAttributeDto | CustomIntegerAttributeDto | CustomDecimalAttributeDto)[] | null;
}
