/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { BooleanSmartFilterDto } from './booleanSmartFilterDto';
import type { BufferSmartFilterDto } from './bufferSmartFilterDto';
import type { DecimalSmartFilterDto } from './decimalSmartFilterDto';
import type { IntegerSmartFilterDto } from './integerSmartFilterDto';
import type { StringSmartFilterDto } from './stringSmartFilterDto';

export interface CreateSmartFilterGroupDto {
  filters: (StringSmartFilterDto | BooleanSmartFilterDto | IntegerSmartFilterDto | DecimalSmartFilterDto | BufferSmartFilterDto)[] | null;
}
