/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */

export type CustomDecimalAttributeDtoType = typeof CustomDecimalAttributeDtoType[keyof typeof CustomDecimalAttributeDtoType];


export const CustomDecimalAttributeDtoType = {
  decimal: 'decimal',
} as const;
