/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { CustomStringAttributeDtoType } from './customStringAttributeDtoType';

export interface CustomStringAttributeDto {
  type: CustomStringAttributeDtoType;
  key: string;
  value: string;
}
