/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */

export type CustomStringAttributeDtoType = typeof CustomStringAttributeDtoType[keyof typeof CustomStringAttributeDtoType];


export const CustomStringAttributeDtoType = {
  string: 'string',
} as const;
