/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */
import type { CustomDecimalAttributeDtoType } from './customDecimalAttributeDtoType';

export interface CustomDecimalAttributeDto {
  type: CustomDecimalAttributeDtoType;
  key: string;
  value: number;
}
