/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */

export type CustomBufferAttributeDtoType = typeof CustomBufferAttributeDtoType[keyof typeof CustomBufferAttributeDtoType];


export const CustomBufferAttributeDtoType = {
  buffer: 'buffer',
} as const;
