/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { CustomBooleanAttributeDtoType } from './customBooleanAttributeDtoType';

export interface CustomBooleanAttributeDto {
  type: CustomBooleanAttributeDtoType;
  key: string;
  value: boolean;
}
