/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type CustomBooleanAttributeDtoType = typeof CustomBooleanAttributeDtoType[keyof typeof CustomBooleanAttributeDtoType];


export const CustomBooleanAttributeDtoType = {
  boolean: 'boolean',
} as const;
