/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */

export type CustomIntegerAttributeDtoType = typeof CustomIntegerAttributeDtoType[keyof typeof CustomIntegerAttributeDtoType];


export const CustomIntegerAttributeDtoType = {
  integer: 'integer',
} as const;
