/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type DecimalSystemConfigOptionType = typeof DecimalSystemConfigOptionType[keyof typeof DecimalSystemConfigOptionType];


export const DecimalSystemConfigOptionType = {
  decimal: 'decimal',
} as const;
