/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { DecimalUpdateSystemConfigOptionDtoType } from './decimalUpdateSystemConfigOptionDtoType';

export interface DecimalUpdateSystemConfigOptionDto {
  type: DecimalUpdateSystemConfigOptionDtoType;
  key: string;
  values: number[];
}
