/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { DecimalAttributeType } from './decimalAttributeType';

export interface DecimalAttribute {
  type: DecimalAttributeType;
  pluginId: string;
  sourceId: string;
  formatted: string[] | null;
  values: number[];
}
