/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { DecimalSmartFilterDtoAttributeType } from './decimalSmartFilterDtoAttributeType';
import type { DecimalSmartFilterDtoEntityType } from './decimalSmartFilterDtoEntityType';

export interface DecimalSmartFilterDto {
  entityType: DecimalSmartFilterDtoEntityType;
  attributeType: DecimalSmartFilterDtoAttributeType;
  attributeKey: string;
  inverse: boolean;
  value?: number;
  min?: number;
  max?: number;
}
