/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */

export type DecimalSmartFilterDtoAttributeType = typeof DecimalSmartFilterDtoAttributeType[keyof typeof DecimalSmartFilterDtoAttributeType];


export const DecimalSmartFilterDtoAttributeType = {
  decimal: 'decimal',
} as const;
