/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type DecimalSmartFilterDtoEntityType = typeof DecimalSmartFilterDtoEntityType[keyof typeof DecimalSmartFilterDtoEntityType];


export const DecimalSmartFilterDtoEntityType = {
  track: 'track',
  artist: 'artist',
  album: 'album',
} as const;
