/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type DecimalWorkflowStepOptionValueType = typeof DecimalWorkflowStepOptionValueType[keyof typeof DecimalWorkflowStepOptionValueType];


export const DecimalWorkflowStepOptionValueType = {
  decimal: 'decimal',
} as const;
