/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type DecimalUpdateSystemConfigOptionDtoType = typeof DecimalUpdateSystemConfigOptionDtoType[keyof typeof DecimalUpdateSystemConfigOptionDtoType];


export const DecimalUpdateSystemConfigOptionDtoType = {
  decimal: 'decimal',
} as const;
