/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */

export type DecimalSearchAttributeDtoEntityType = typeof DecimalSearchAttributeDtoEntityType[keyof typeof DecimalSearchAttributeDtoEntityType];


export const DecimalSearchAttributeDtoEntityType = {
  track: 'track',
  artist: 'artist',
  album: 'album',
} as const;
