/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */

export type DecimalSearchAttributeDtoType = typeof DecimalSearchAttributeDtoType[keyof typeof DecimalSearchAttributeDtoType];


export const DecimalSearchAttributeDtoType = {
  decimal: 'decimal',
} as const;
