/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { DecimalWorkflowStepOptionValueDtoType } from './decimalWorkflowStepOptionValueDtoType';

export interface DecimalWorkflowStepOptionValueDto {
  id: string;
  type: DecimalWorkflowStepOptionValueDtoType;
  value: number | null;
}
