/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { DecimalSearchAttributeDtoEntityType } from './decimalSearchAttributeDtoEntityType';
import type { DecimalSearchAttributeDtoType } from './decimalSearchAttributeDtoType';

export interface DecimalSearchAttributeDto {
  entityType: DecimalSearchAttributeDtoEntityType;
  type: DecimalSearchAttributeDtoType;
  key: string;
  exists?: boolean;
  decimal?: number;
  min?: number;
  max?: number;
}
