/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type EnumWorkflowStepOptionValueDtoType = typeof EnumWorkflowStepOptionValueDtoType[keyof typeof EnumWorkflowStepOptionValueDtoType];


export const EnumWorkflowStepOptionValueDtoType = {
  enum: 'enum',
} as const;
