/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { EnumWorkflowStepOptionValueType } from './enumWorkflowStepOptionValueType';
import type { WorkspaceStepOptionEnumItem } from './workspaceStepOptionEnumItem';

export interface EnumWorkflowStepOptionValue {
  id: string;
  type: EnumWorkflowStepOptionValueType;
  value: string | null;
  options: WorkspaceStepOptionEnumItem[];
}
