/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type EnumWorkflowStepOptionValueType = typeof EnumWorkflowStepOptionValueType[keyof typeof EnumWorkflowStepOptionValueType];


export const EnumWorkflowStepOptionValueType = {
  enum: 'enum',
} as const;
