/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { AttributeMap } from './attributeMap';
import type { TrackArtist } from './trackArtist';

export interface EphemeralTrack {
  trackId: string;
  pluginId: string;
  libraryId: string;
  title: string;
  attributes: AttributeMap | null;
  artists: TrackArtist[] | null;
}
