/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { AttributeMap } from './attributeMap';

export interface EphemeralTrack {
  id: string;
  pluginId: string;
  libraryId: string;
  title: string;
  attributes: AttributeMap | null;
}
