/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { FilterableAttributeEntityType } from './filterableAttributeEntityType';

export interface FilterableAttribute {
  entityType: FilterableAttributeEntityType;
  attributeKey: string;
  attributeType: string;
  label?: string | null;
  supportsFuzzy?: boolean | null;
}
