/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */

export type GetOwnPlaybackHistoryParams = {
/**
 * @minimum 1
 * @maximum 100
 */
pageSize: number;
/**
 * @minimum 1
 */
page: number;
pluginId?: string;
clientName?: string;
};
