/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type GetPlaylistParams = {
/**
 * Maximum number of tracks to include
 * @minimum 0
 * @maximum 200
 */
tracks?: number;
};
