/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { IdentifierType } from './identifierType';

export interface IdentifierKeyDto {
  pluginId: string;
  identifierId: string;
  type: IdentifierType;
}
