/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export interface Identity {
  pluginId: string;
  identityId: string;
  value: string;
  ordinal: number;
}
