/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */

export type IdentifierTarget = typeof IdentifierTarget[keyof typeof IdentifierTarget];


export const IdentifierTarget = {
  track: 'track',
  artist: 'artist',
  album: 'album',
} as const;
