/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type IntegerSmartFilterDtoAttributeType = typeof IntegerSmartFilterDtoAttributeType[keyof typeof IntegerSmartFilterDtoAttributeType];


export const IntegerSmartFilterDtoAttributeType = {
  integer: 'integer',
} as const;
