/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { AttributeEntity } from './attributeEntity';

export interface IntegerSmartPlaylistFilter {
  uuid: string;
  entityType: AttributeEntity;
  attributeKey: string;
  attributeType: 'integer';
  inverse: boolean;
  value: number | null;
  min: number | null;
  max: number | null;
}
