/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type IntegerWorkflowStepOptionValueType = typeof IntegerWorkflowStepOptionValueType[keyof typeof IntegerWorkflowStepOptionValueType];


export const IntegerWorkflowStepOptionValueType = {
  integer: 'integer',
} as const;
