/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { IntegerWorkflowStepOptionValueDtoType } from './integerWorkflowStepOptionValueDtoType';

export interface IntegerWorkflowStepOptionValueDto {
  id: string;
  type: IntegerWorkflowStepOptionValueDtoType;
  value: number | null;
}
