/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type IntegerSmartFilterDtoEntityType = typeof IntegerSmartFilterDtoEntityType[keyof typeof IntegerSmartFilterDtoEntityType];


export const IntegerSmartFilterDtoEntityType = {
  track: 'track',
  artist: 'artist',
  album: 'album',
} as const;
