/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */

export type IntegerSearchAttributeDtoEntityType = typeof IntegerSearchAttributeDtoEntityType[keyof typeof IntegerSearchAttributeDtoEntityType];


export const IntegerSearchAttributeDtoEntityType = {
  track: 'track',
  artist: 'artist',
  album: 'album',
} as const;
