/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */

export type IntegerSearchAttributeDtoType = typeof IntegerSearchAttributeDtoType[keyof typeof IntegerSearchAttributeDtoType];


export const IntegerSearchAttributeDtoType = {
  integer: 'integer',
} as const;
