/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { IntegerUpdateSystemConfigOptionDtoType } from './integerUpdateSystemConfigOptionDtoType';

export interface IntegerUpdateSystemConfigOptionDto {
  type: IntegerUpdateSystemConfigOptionDtoType;
  key: string;
  values: number[];
}
