/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */

export type IntegerAttributeType = typeof IntegerAttributeType[keyof typeof IntegerAttributeType];


export const IntegerAttributeType = {
  integer: 'integer',
} as const;
