/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type IntegerSystemConfigOptionType = typeof IntegerSystemConfigOptionType[keyof typeof IntegerSystemConfigOptionType];


export const IntegerSystemConfigOptionType = {
  integer: 'integer',
} as const;
