/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { IntegerWorkflowStepOptionValueType } from './integerWorkflowStepOptionValueType';

export interface IntegerWorkflowStepOptionValue {
  id: string;
  type: IntegerWorkflowStepOptionValueType;
  value: number | null;
}
