/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { IntegerSearchAttributeDtoEntityType } from './integerSearchAttributeDtoEntityType';
import type { IntegerSearchAttributeDtoType } from './integerSearchAttributeDtoType';

export interface IntegerSearchAttributeDto {
  entityType: IntegerSearchAttributeDtoEntityType;
  type: IntegerSearchAttributeDtoType;
  key: string;
  exists?: boolean;
  integer?: number;
  min?: number;
  max?: number;
}
