/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { IntegerSystemConfigOptionType } from './integerSystemConfigOptionType';

export interface IntegerSystemConfigOption {
  type: IntegerSystemConfigOptionType;
  key: string;
  supportsMultiple: boolean;
  values: number[];
  min: number | null;
  max: number | null;
}
