/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { IntegerSmartFilterDtoAttributeType } from './integerSmartFilterDtoAttributeType';
import type { IntegerSmartFilterDtoEntityType } from './integerSmartFilterDtoEntityType';

export interface IntegerSmartFilterDto {
  entityType: IntegerSmartFilterDtoEntityType;
  attributeType: IntegerSmartFilterDtoAttributeType;
  attributeKey: string;
  inverse: boolean;
  value?: number;
  min?: number;
  max?: number;
}
