/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { IntegerAttributeType } from './integerAttributeType';

export interface IntegerAttribute {
  type: IntegerAttributeType;
  pluginId: string;
  sourceId: string;
  /** @nullable */
  formatted: string[] | null;
  values: number[];
}
