/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */
import type { LoadedPluginUpdateStatus } from './loadedPluginUpdateStatus';

export interface LoadedPlugin {
  name: string;
  version: string;
  description: string | null;
  updateStatus: LoadedPluginUpdateStatus;
}
