/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */

export type LoadedPluginUpdateStatus = typeof LoadedPluginUpdateStatus[keyof typeof LoadedPluginUpdateStatus];


export const LoadedPluginUpdateStatus = {
  unsupported: 'unsupported',
  not_checked: 'not_checked',
  has_update: 'has_update',
  up_to_date: 'up_to_date',
  updating: 'updating',
} as const;
