/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { LoadedAttributeType } from './loadedAttributeType';

export interface LoadedAttribute {
  pluginId: string;
  sourceId: string;
  key: string;
  type: LoadedAttributeType;
  supportsMultiple: boolean;
}
