/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export interface MarketplacePlugin {
  id: string;
  name: string;
  description: string | null;
  authorName: string;
  authorUrl: string | null;
  url: string | null;
  repository: string;
  marketplaceUuid: string;
  marketplaceName: string;
  installed: boolean;
}
