/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export interface Marketplace {
  uuid: string;
  url: string;
  name: string | null;
  pluginCount: number | null;
  reachable: boolean;
  addedAt: number;
}
