/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export interface NewPlaylistTrackDto {
  pluginId: string;
  libraryId: string;
  trackId: string;
}
