/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type ParagraphConfigNodeType = typeof ParagraphConfigNodeType[keyof typeof ParagraphConfigNodeType];


export const ParagraphConfigNodeType = {
  paragraph: 'paragraph',
} as const;
