/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { PlaylistMemberRole } from './playlistMemberRole';
import type { User } from './user';

export interface PlaylistMember {
  userUuid: string;
  user: User | null;
  role: PlaylistMemberRole;
  dateAdded: Date;
}
