/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { AttributeMap } from './attributeMap';
import type { PlaylistTrack } from './playlistTrack';
import type { User } from './user';

export interface Playlist {
  uuid: string;
  ownerUuid: string;
  owner: User | null;
  attributes: AttributeMap | null;
  /** @nullable */
  tracks: PlaylistTrack[] | null;
}
