/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */

export interface PlaylistTracksQuery {
  /**
     * @minimum 0
     * @maximum 1000
     */
  amount: number;
  /** @minimum 0 */
  offset: number;
}
