/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { Track } from './track';
import type { User } from './user';

export interface PlaylistTrack {
  track: Track;
  dateAdded: Date;
  addedBySystem: boolean;
  addedBy: User | null;
}
