/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type PlaylistMemberRole = typeof PlaylistMemberRole[keyof typeof PlaylistMemberRole];


export const PlaylistMemberRole = {
  collaborator: 'collaborator',
  viewer: 'viewer',
} as const;
