/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { Track } from './track';

export interface PlaybackHistoryEntry {
  trackUuid: string;
  pluginId: string | null;
  clientName: string;
  datePlayed: Date;
  dateRecorded: Date;
  track: Track | null;
}
