/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */
import type { PlaybackHistoryEntry } from './playbackHistoryEntry';

export interface PlaybackHistoryPage {
  entries: PlaybackHistoryEntry[];
  total: number;
}
