/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */

export type PlaylistVisibility = typeof PlaylistVisibility[keyof typeof PlaylistVisibility];


export const PlaylistVisibility = {
  public: 'public',
  unlisted: 'unlisted',
  private: 'private',
} as const;
