/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { PlaylistTrackAddedBy } from './playlistTrackAddedBy';
import type { Track } from './track';

export interface PlaylistTrack {
  track: Track;
  dateAdded: Date;
  /** @nullable */
  addedBySystem: boolean | null;
  /** @nullable */
  addedBy: PlaylistTrackAddedBy;
}
