/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { AttributeMap } from './attributeMap';
import type { PlaylistMember } from './playlistMember';
import type { PlaylistOwnerUuid } from './playlistOwnerUuid';
import type { PlaylistTrack } from './playlistTrack';
import type { PlaylistVisibility } from './playlistVisibility';
import type { SmartPlaylistFilterGroup } from './smartPlaylistFilterGroup';
import type { User } from './user';

export interface Playlist {
  uuid: string;
  ownerUuid: PlaylistOwnerUuid;
  owner: User | null;
  dateCreated: Date;
  dateModified: Date;
  visibility: PlaylistVisibility;
  attributes: AttributeMap | null;
  filterGroups: SmartPlaylistFilterGroup[] | null;
  tracks: PlaylistTrack[] | null;
  trackCount: number | null;
  members: PlaylistMember[] | null;
}
