/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { HeadingConfigNode } from './headingConfigNode';
import type { ParagraphConfigNode } from './paragraphConfigNode';
import type { SectionConfigNode } from './sectionConfigNode';
import type { TextConfigNode } from './textConfigNode';

export interface PluginConfig {
  node: TextConfigNode | HeadingConfigNode | SectionConfigNode | ParagraphConfigNode;
}
