/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */

export interface ReportPlaybackDto {
  pluginId: string;
  libraryId: string;
  trackId: string;
  clientName: string;
  datePlayed?: Date;
}
