/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { ResourceSha256 } from './resourceSha256';

export interface Resource {
  uuid: string;
  url: string;
  extension: string;
  /** @nullable */
  sha256: ResourceSha256;
}
