/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { Album } from './album';
import type { Artist } from './artist';
import type { Track } from './track';

export interface SearchResults {
  tracks: Track[];
  artists: Artist[];
  albums: Album[];
}
