/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { FilterableAttribute } from './filterableAttribute';
import type { SortMethod } from './sortMethod';

export interface SearchSource {
  pluginId: string;
  sourceId: string;
  name: string;
  sortMethods?: SortMethod[] | null;
  filterableAttributes?: FilterableAttribute[] | null;
}
