/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type SearchSortDtoDirection = typeof SearchSortDtoDirection[keyof typeof SearchSortDtoDirection];


export const SearchSortDtoDirection = {
  asc: 'asc',
  desc: 'desc',
} as const;
