/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { BooleanSearchAttributeDto } from './booleanSearchAttributeDto';
import type { BufferSearchAttributeDto } from './bufferSearchAttributeDto';
import type { DecimalSearchAttributeDto } from './decimalSearchAttributeDto';
import type { IntegerSearchAttributeDto } from './integerSearchAttributeDto';
import type { SearchSortDto } from './searchSortDto';
import type { StringSearchAttributeDto } from './stringSearchAttributeDto';

export interface SearchDto {
  withTracks: boolean;
  withAlbums: boolean;
  withArtists: boolean;
  attributes: (StringSearchAttributeDto | BooleanSearchAttributeDto | IntegerSearchAttributeDto | DecimalSearchAttributeDto | BufferSearchAttributeDto)[] | null;
  query?: string;
  sort?: SearchSortDto;
}
