/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type SectionConfigNodeType = typeof SectionConfigNodeType[keyof typeof SectionConfigNodeType];


export const SectionConfigNodeType = {
  section: 'section',
} as const;
