/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { BooleanSmartPlaylistFilter } from './booleanSmartPlaylistFilter';
import type { BufferSmartPlaylistFilter } from './bufferSmartPlaylistFilter';
import type { DecimalSmartPlaylistFilter } from './decimalSmartPlaylistFilter';
import type { IntegerSmartPlaylistFilter } from './integerSmartPlaylistFilter';
import type { StringSmartPlaylistFilter } from './stringSmartPlaylistFilter';

export interface SmartPlaylistFilterGroup {
  uuid: string;
  dateCreated: Date;
  filters: (StringSmartPlaylistFilter | BooleanSmartPlaylistFilter | IntegerSmartPlaylistFilter | DecimalSmartPlaylistFilter | BufferSmartPlaylistFilter)[];
}
