/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.2.0
 */

export interface SortMethod {
  key: string;
  label?: string | null;
  ascending: boolean;
  descending: boolean;
}
