/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */

export type StreamInstanceType = typeof StreamInstanceType[keyof typeof StreamInstanceType];


export const StreamInstanceType = {
  hls: 'hls',
  stream: 'stream',
} as const;
