/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { StringWorkflowStepOptionValueDtoType } from './stringWorkflowStepOptionValueDtoType';

export interface StringWorkflowStepOptionValueDto {
  id: string;
  type: StringWorkflowStepOptionValueDtoType;
  value: string | null;
}
