/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */

export type StringSearchAttributeDtoType = typeof StringSearchAttributeDtoType[keyof typeof StringSearchAttributeDtoType];


export const StringSearchAttributeDtoType = {
  string: 'string',
} as const;
