/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */

export type StringSmartFilterDtoAttributeType = typeof StringSmartFilterDtoAttributeType[keyof typeof StringSmartFilterDtoAttributeType];


export const StringSmartFilterDtoAttributeType = {
  string: 'string',
} as const;
