/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { StringWorkflowStepOptionValueType } from './stringWorkflowStepOptionValueType';

export interface StringWorkflowStepOptionValue {
  id: string;
  type: StringWorkflowStepOptionValueType;
  value: string | null;
}
