/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { StringAttributeType } from './stringAttributeType';

export interface StringAttribute {
  type: StringAttributeType;
  pluginId: string;
  sourceId: string;
  formatted: string[] | null;
  values: string[];
}
