/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { AttributeEntity } from './attributeEntity';

export interface StringSmartPlaylistFilter {
  uuid: string;
  entityType: AttributeEntity;
  attributeKey: string;
  attributeType: 'string';
  inverse: boolean;
  value: string | null;
  partial: boolean;
}
