/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { StringSmartFilterDtoAttributeType } from './stringSmartFilterDtoAttributeType';
import type { StringSmartFilterDtoEntityType } from './stringSmartFilterDtoEntityType';

export interface StringSmartFilterDto {
  entityType: StringSmartFilterDtoEntityType;
  attributeType: StringSmartFilterDtoAttributeType;
  attributeKey: string;
  inverse: boolean;
  value?: string;
  partial?: boolean;
}
