/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { StringSystemConfigOptionType } from './stringSystemConfigOptionType';

export interface StringSystemConfigOption {
  type: StringSystemConfigOptionType;
  key: string;
  supportsMultiple: boolean;
  values: string[];
  minLength: number | null;
  maxLength: number | null;
}
