/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type StringSystemConfigOptionType = typeof StringSystemConfigOptionType[keyof typeof StringSystemConfigOptionType];


export const StringSystemConfigOptionType = {
  string: 'string',
} as const;
