/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type StringWorkflowStepOptionValueType = typeof StringWorkflowStepOptionValueType[keyof typeof StringWorkflowStepOptionValueType];


export const StringWorkflowStepOptionValueType = {
  string: 'string',
} as const;
