/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export type StringWorkflowStepOptionValueDtoType = typeof StringWorkflowStepOptionValueDtoType[keyof typeof StringWorkflowStepOptionValueDtoType];


export const StringWorkflowStepOptionValueDtoType = {
  string: 'string',
} as const;
