/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { StringSearchAttributeDtoEntityType } from './stringSearchAttributeDtoEntityType';
import type { StringSearchAttributeDtoType } from './stringSearchAttributeDtoType';

export interface StringSearchAttributeDto {
  entityType: StringSearchAttributeDtoEntityType;
  type: StringSearchAttributeDtoType;
  key: string;
  exists?: boolean;
  query?: string;
  partial?: boolean;
}
