/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */

export type StringUpdateSystemConfigOptionDtoType = typeof StringUpdateSystemConfigOptionDtoType[keyof typeof StringUpdateSystemConfigOptionDtoType];


export const StringUpdateSystemConfigOptionDtoType = {
  string: 'string',
} as const;
