/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { StringUpdateSystemConfigOptionDtoType } from './stringUpdateSystemConfigOptionDtoType';

export interface StringUpdateSystemConfigOptionDto {
  type: StringUpdateSystemConfigOptionDtoType;
  key: string;
  values: string[];
}
