/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { BooleanSystemConfigOption } from './booleanSystemConfigOption';
import type { DecimalSystemConfigOption } from './decimalSystemConfigOption';
import type { IntegerSystemConfigOption } from './integerSystemConfigOption';
import type { StringSystemConfigOption } from './stringSystemConfigOption';

export interface SystemConfigOptions {
  options: (StringSystemConfigOption | IntegerSystemConfigOption | DecimalSystemConfigOption | BooleanSystemConfigOption)[];
}
