/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskStatus } from './taskStatus';

export interface Task {
  uuid: string;
  pluginId: string | null;
  taskId: string;
  subTasks: string[] | null;
  status: TaskStatus;
  /**
     * @minimum 0
     * @maximum 100
     */
  percent: number | null;
  resumable: boolean;
}
