/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { TextConfigNodeType } from './textConfigNodeType';

export interface TextConfigNode {
  type: TextConfigNodeType;
  id: string;
  name: string;
  value: string;
  placeholder?: string | null;
}
