/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.2
 */
import type { Artist } from './artist';

export interface TrackArtist {
  artistUuid: string;
  artist: Artist;
  joinPhrase: string | null;
}
