/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */

export interface TrackCreationSession {
  uuid: string;
  dateStarted: Date;
  /**
     * @minimum 0
     * @maximum 100
     */
  percent: number | null;
}
