/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { Album } from './album';
import type { AttributeMap } from './attributeMap';
import type { Identity } from './identity';
import type { TrackArtist } from './trackArtist';

export interface Track {
  trackId: string;
  pluginId: string;
  libraryId: string;
  title: string;
  dateAdded: Date;
  artists: TrackArtist[] | null;
  albums: Album[] | null;
  attributes: AttributeMap | null;
  identities: Identity[] | null;
}
