/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { CustomBooleanAttributeDto } from './customBooleanAttributeDto';
import type { CustomBufferAttributeDto } from './customBufferAttributeDto';
import type { CustomDecimalAttributeDto } from './customDecimalAttributeDto';
import type { CustomIntegerAttributeDto } from './customIntegerAttributeDto';
import type { CustomStringAttributeDto } from './customStringAttributeDto';

export interface UpdatePlaylistAttributesDto {
  attributes: (CustomStringAttributeDto | CustomBooleanAttributeDto | CustomIntegerAttributeDto | CustomDecimalAttributeDto | CustomBufferAttributeDto)[] | null;
}
