/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { BooleanWorkflowStepOptionValueDto } from './booleanWorkflowStepOptionValueDto';
import type { DecimalWorkflowStepOptionValueDto } from './decimalWorkflowStepOptionValueDto';
import type { EnumWorkflowStepOptionValueDto } from './enumWorkflowStepOptionValueDto';
import type { IntegerWorkflowStepOptionValueDto } from './integerWorkflowStepOptionValueDto';
import type { StringWorkflowStepOptionValueDto } from './stringWorkflowStepOptionValueDto';

export interface UpdateWorkflowStepOptionsDto {
  options: (StringWorkflowStepOptionValueDto | EnumWorkflowStepOptionValueDto | BooleanWorkflowStepOptionValueDto | IntegerWorkflowStepOptionValueDto | DecimalWorkflowStepOptionValueDto)[];
}
