/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.1.0
 */
import type { BooleanUpdateSystemConfigOptionDto } from './booleanUpdateSystemConfigOptionDto';
import type { DecimalUpdateSystemConfigOptionDto } from './decimalUpdateSystemConfigOptionDto';
import type { IntegerUpdateSystemConfigOptionDto } from './integerUpdateSystemConfigOptionDto';
import type { StringUpdateSystemConfigOptionDto } from './stringUpdateSystemConfigOptionDto';

export interface UpdateSystemConfigOptionsDto {
  options: (StringUpdateSystemConfigOptionDto | BooleanUpdateSystemConfigOptionDto | IntegerUpdateSystemConfigOptionDto | DecimalUpdateSystemConfigOptionDto)[];
}
