/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.4
 */
import type { WorkflowStepType } from './workflowStepType';

export interface WorkflowStepDefinition {
  pluginId: string | null;
  stepId: string;
  stepType: WorkflowStepType;
}
