/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.3
 */
import type { BooleanWorkflowStepOptionValue } from './booleanWorkflowStepOptionValue';
import type { DecimalWorkflowStepOptionValue } from './decimalWorkflowStepOptionValue';
import type { EnumWorkflowStepOptionValue } from './enumWorkflowStepOptionValue';
import type { IntegerWorkflowStepOptionValue } from './integerWorkflowStepOptionValue';
import type { StringWorkflowStepOptionValue } from './stringWorkflowStepOptionValue';
import type { WorkflowStepType } from './workflowStepType';

export interface WorkflowStep {
  uuid: string;
  workflowUuid: string;
  stepType: WorkflowStepType;
  pluginId: string | null;
  stepId: string;
  loaded: boolean;
  options: (StringWorkflowStepOptionValue | BooleanWorkflowStepOptionValue | IntegerWorkflowStepOptionValue | DecimalWorkflowStepOptionValue | EnumWorkflowStepOptionValue)[] | null;
}
